osx_image: xcode13.2
language: objective-c
cache:
  cocoapods: true
  bundler: true
xcode_workspace: WeShop.xcworkspace
xcode_scheme: WeShop AppStore
before_install:
- brew install gimme
- GIMME_GO_VERSION=1.11.x
install:
- export XCPRETTY_FORMATTER="$(bundle show xcpretty-json-formatter)/lib/json_formatter.rb"
